### ISSUE TITLE
Do not require `Encode`/`Decode` trait bounds for `#[codec(compact)]`

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-codec#38]
Auto deriving `Encode`/`Decode` for structs with generic types, that have the `#[codec(compact)]` attribute, should just get the `HasCompact` bound added.

**Comment by thiolliere** [comment]
notes: (this is not as easy as it looks)
* First Encode/Decode should not be pushed when used in `#[codec(compact)]` nor `#[encoded_as(...)]`
* A generic type could be used on different fields, thus we can't just look at attributed field.
```rust
struct Foo<A> {
    a: A,
    #[codec(Compact)]
    b: A,
}
```

* Pushing Encode/Decode when user would require it is actually difficult. current implementation leads to pushes when user wouldn't require it:

```rust
struct Foo<A> {
}
impl Encode for Foo<A> where A: SomeUserDefinedTrait {}

#[derive(Encode)]
// Here A would be bound to Encode also which user may not want to
struct Bar<A: SomeUserDefinedTrait> {
    f: Foo<A>
}
```

My thought: I am usually not in favor of auto bound add. But I could work on the following implementation:
if generic is used in tuple, array, slice, Vec, ... everything where actual Encode trait is auto deriving for. then push Encode/Decode,
if generic is used as is in `#[compact]` then we push HasCompact
