### ISSUE TITLE
Decode is not implemented for `u8`

### ISSUE THREAD

**Issue by xlc** [paritytech/parity-codec#47]
What is the reason `u8` is not here? even `i8` is included.
This means `Decode` is not implemented for `[u8]` as well

https://github.com/paritytech/parity-codec/blob/50ea4fc9c74a426720ff62ed166c9ced485cac89/src/codec.rs#L1006-L1007

Original issue: https://github.com/paritytech/substrate/pull/1804#issuecomment-465741529

**Comment by gavofyork** [comment]
Because it would otherwise make the two encodings: `Vec<u8>` and `Vec<T: Codec>` clash.

**Comment by xlc** [comment]
In that case can we have `Decode` implemented for `[u8]`? There is `Encode` for `[u8]`, it doesn't make much sense to not have `Decode`

**Comment by bkchr** [comment]
You can not implement `Decode` for `[u8]`. How do you want to decode to a slice?
