### ISSUE TITLE
rename to `scale-codec`

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/parity-codec#80]
[Doc and spec](https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf) and [other implementations](https://github.com/polkascan/py-scale-codec) refer to this codec as `Simple Concatenating Aggregated Little Endians` - short SCALE - codec. I suggest we rename this repo and crate to use the same name.

**Comment by bkchr** [comment]
I propose `parity-scale-codec`.
